local theme = {}
C = require('colors')

theme.highlights = {
  -- code syntax
  ErrorMsg = { fg = C.red[1], bg = C.bg, bold = true },
  Constant = { fg = C.orange[1] },
  String = { fg = C.green[1] },
  Character = { fg = C.green[1] },
  Variable = { fg = C.white[1] },
  Number = { fg = C.orange[1] },
  Float = { fg = C.orange[1] },
  Boolean = { fg = C.orange[1] },
  Function = { fg = C.purple[3] },
  Keyword = { fg = C.purple[2], italic = true },
  Conditional = { fg = C.purple[2] },
  Repeat = { fg = C.purple[2] },
  Operator = { fg = C.purple[1] },
  Comment = { fg = C.blue_gray[1], italic = true },
  Type = { fg = C.cyan[1] },
  PreProc = { fg = C.purple[2] },
  Include = { fg = C.purple[2] },
  Exception = { fg = C.purple[2] },
  Structure = { fg = C.cyan[1] },
  Typedef = { fg = C.purple[2] },
  Define = { fg = C.purple[2] },
  Macro = { fg = C.purple[2] },
  Debug = { fg = C.purple[2] },
  Statement = { fg = C.purple[2] },
  Identifier = { fg = "#bb9af7" },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Title = { fg = C.cyan[3], bold = true },

  -- editor
  Normal = { fg = C.fg, bg = C.bg },
  NormalNC = { fg = C.fg, bg = C.bg },
  Visual = { bg = C.cyan[2] },
  SignColumn = { fg = C.none, bg = C.bg },
  ColorColumn = { bg = C.black },
  MsgArea = { fg = C.indigo[1] },
  ModeMsg = { fg = C.black, bold = true },
  Directory = { fg = C.cyan[1] },
  DiffAdd = { bg = C.green[1] },
  DiffChange = { bg = C.cyan[1] },
  DiffDelete = { bg = C.red[1] },
  DiffText = { bg = C.cyan[2] },
  EndOfBuffer = { fg = C.bg },
  VertSplit = { fg = C.blue_gray[1] },
  WinSeparator = { fg = C.blue_gray[1], bold = true },
  Substitute = { bg = C.red[1], fg = C.black },
  SpellBad = { sp = C.red[1], undercurl = true },
  SpellCap = { sp = C.yellow[1], undercurl = true },
  SpellLocal = { sp = C.cyan[1], undercurl = true },
  SpellRare = { sp = C.green[1], undercurl = true },
  Pmenu = { bg = C.black, fg = C.fg },
  PmenuSel = { bg = C.indigo[2] },
  PmenuSbar = { bg = C.bg },
  PmenuThumb = { bg = C.indigo[1] },
  WildMenu = { bg = C.cyan[2] },
  LineNr = { fg = C.indigo[1] },
  Whitespace = { fg = C.bg },
  CursorIM = { fg = C.bg, bg = C.fg },
  CursorColumn = { bg = "#292e42" },
  CursorLine = { bg = "#292e42" },
  QuickFixLine = { bg = C.cyan[2], bold = true },

  -- buffers
  BufferCurrent = { bg = C.indigo[1], fg = C.fg },
  BufferCurrentIndex = { bg = C.indigo[1], fg = C.cyan[3] },
  BufferCurrentMod = { bg = C.indigo[1], fg = C.yellow[1] },
  BufferCurrentSign = { bg = C.indigo[1], fg = C.cyan[2] },
  BufferCurrentTarget = { bg = C.indigo[1], fg = C.red[1] },
  BufferVisible = { bg = C.indigo[2], fg = C.fg },
  BufferVisibleIndex = { bg = C.indigo[2], fg = C.cyan[2] },
  BufferVisibleMod = { bg = C.indigo[2], fg = C.yellow[1] },
  BufferVisibleSign = { bg = C.indigo[2], fg = C.cyan[2] },
  BufferVisibleTarget = { bg = C.indigo[2], fg = C.red[1] },
  BufferInactive = { bg = C.indigo[2], fg = C.blue_gray[1] },
  BufferInactiveIndex = { bg = C.indigo[2], fg = C.blue_gray[1] },
  BufferInactiveMod = { bg = C.indigo[2], fg = C.yellow[1] },
  BufferInactiveSign = { bg = C.indigo[2], fg = C.cyan[3] },
  BufferInactiveTarget = { bg = C.indigo[2], fg = C.red[1] },
  BufferTabpages = { bg = C.indigo[2], fg = C.none },
  BufferTabpage = { bg = C.indigo[2], fg = C.cyan[3] },

  -- lsp
  LspReferenceText = { bg = C.indigo[1] },
  LspReferenceRead = { bg = C.indigo[1] },
  LspReferenceWrite = { bg = C.indigo[1] },
}

return theme
